### ISSUE TITLE
Questions about the run time

### ISSUE THREAD

**Issue by echoofluoc** [HaoZhang1018/SDNet#3]
Hi, thanks for sharing your code!
I download the code from this repository and just repalce the images in the IR_VIS folder to see the performance.
The images I used is from RoadScene dataset (size about 500x400), although the images' resolution are not strictly same, I find the run time is **quite** different from what is reported in your paper.
Is this possible or Is there anything I should take care of? Looking forward to your helpful reply.

By the way, I run the code on a fully empty Titan Xp GPU and there is no other remarkable program runs in 64G memory CPU.

> 2021-11-21 20:33:22.551195: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-11-21 20:33:23.726314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 11.91GiB freeMemory: 11.75GiB
2021-11-21 20:33:23.956254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 11.91GiB freeMemory: 11.75GiB
2021-11-21 20:33:23.957564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1
2021-11-21 20:33:24.679765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-21 20:33:24.679818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1 
2021-11-21 20:33:24.679827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N Y 
2021-11-21 20:33:24.679832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y N 
2021-11-21 20:33:24.680480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11370 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:02:00.0, compute capability: 6.1)
2021-11-21 20:33:24.813198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11370 MB memory) -> physical GPU (device: 1, name: TITAN Xp, pci bus id: 0000:03:00.0, compute capability: 6.1)
Testing [0] success,Testing time is [0.892022]
Testing [1] success,Testing time is [0.077229]
Testing [2] success,Testing time is [0.082870]
Testing [3] success,Testing time is [0.077784]
Testing [4] success,Testing time is [0.072668]
Testing [5] success,Testing time is [0.062164]
Testing [6] success,Testing time is [0.089169]
Testing [7] success,Testing time is [0.087192]
Testing [8] success,Testing time is [0.095721]
Testing [9] success,Testing time is [0.078409]
Testing [10] success,Testing time is [0.061006]
Testing [11] success,Testing time is [0.096850]
Testing [12] success,Testing time is [0.084235]
Testing [13] success,Testing time is [0.071003]
Testing [14] success,Testing time is [0.079572]
Testing [15] success,Testing time is [0.073389]
Testing [16] success,Testing time is [0.091420]
Testing [17] success,Testing time is [0.103578]
Testing [18] success,Testing time is [0.077224]
Testing [19] success,Testing time is [0.073534]

**Comment by HaoZhang1018** [comment]
> Hi, thanks for sharing your code! I download the code from this repository and just repalce the images in the IR_VIS folder to see the performance. The images I used is from RoadScene dataset (size about 500x400), although the images' resolution are not strictly same, I find the run time is **quite** different from what is reported in your paper. Is this possible or Is there anything I should take care of? Looking forward to your helpful reply.
> 
> By the way, I run the code on a fully empty Titan Xp GPU and there is no other remarkable program runs in 64G memory CPU.
> 
> > 2021-11-21 20:33:22.551195: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> > 2021-11-21 20:33:23.726314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties:
> > name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
> > pciBusID: 0000:02:00.0
> > totalMemory: 11.91GiB freeMemory: 11.75GiB
> > 2021-11-21 20:33:23.956254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties:
> > name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
> > pciBusID: 0000:03:00.0
> > totalMemory: 11.91GiB freeMemory: 11.75GiB
> > 2021-11-21 20:33:23.957564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1
> > 2021-11-21 20:33:24.679765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
> > 2021-11-21 20:33:24.679818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1
> > 2021-11-21 20:33:24.679827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N Y
> > 2021-11-21 20:33:24.679832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y N
> > 2021-11-21 20:33:24.680480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11370 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:02:00.0, compute capability: 6.1)
> > 2021-11-21 20:33:24.813198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11370 MB memory) -> physical GPU (device: 1, name: TITAN Xp, pci bus id: 0000:03:00.0, compute capability: 6.1)
> > Testing [0] success,Testing time is [0.892022]
> > Testing [1] success,Testing time is [0.077229]
> > Testing [2] success,Testing time is [0.082870]
> > Testing [3] success,Testing time is [0.077784]
> > Testing [4] success,Testing time is [0.072668]
> > Testing [5] success,Testing time is [0.062164]
> > Testing [6] success,Testing time is [0.089169]
> > Testing [7] success,Testing time is [0.087192]
> > Testing [8] success,Testing time is [0.095721]
> > Testing [9] success,Testing time is [0.078409]
> > Testing [10] success,Testing time is [0.061006]
> > Testing [11] success,Testing time is [0.096850]
> > Testing [12] success,Testing time is [0.084235]
> > Testing [13] success,Testing time is [0.071003]
> > Testing [14] success,Testing time is [0.079572]
> > Testing [15] success,Testing time is [0.073389]
> > Testing [16] success,Testing time is [0.091420]
> > Testing [17] success,Testing time is [0.103578]
> > Testing [18] success,Testing time is [0.077224]
> > Testing [19] success,Testing time is [0.073534]

Hi. I think there are two reasons that may cause this phenomenon. i) Performance differences between Gpus.  The experiments in SDNet are performed in GPU RTX 2080Ti. And RTX 2080Ti has higher running velocity than Titan Xp. ii) Consideration of the decomposition. In the provided "test.py", both the squeeze network and the decomposition network are tested.  In fact, all that is really needed is a squeeze network for data fusion. Hope it is of help to you.

**Comment by echoofluoc** [comment]
Thanks for your helpful and instant reply!
For ii), I tried to comment the Layer 6 ~ Layer9 in the fusion model(Line 101~145 of "test.py") for keeping pure squeeze network, which didn't bring notable run time improvement.

For i), I think the performance differences between GPU is not the dominant reason because the run time difference is quite large between TitanXp and 2080Ti.(0.07 v.s. 0.007). 
However, after checking the code "test_one_image.py" from [STDFusion](https://github.com/Linfeng-Tang/STDFusionNet), which is also from your team. I find the result 0.007s could be reproduced when I run the second routine with the model you provide.
To make it clearly, I make tiny modifications to the "test.py" of SDNet as follow:
Beginning at Line 167 in "test.py"
**Without modifications :**
`for idx_num in range(10,11):`
 `num_epoch=idx_num`
`  while(num_epoch==idx_num):`
`......`
**With modifications :**
`for idx_num in range(10,12):`
 `idx_num=10`
 `num_epoch=idx_num`
`  while(num_epoch==idx_num):`
`......`

Now, in the first cyclic routine I still get results around 0.07s, but in the second cyclic routine I can get the 0.007s result. I have search this phenomenon online and find it may be caused by the characteristic of tensorflow 1.x asynchronous calculation graph. Because, TensorFlow builds a graph first (which is comparably time consuming) using all the information available and "optimizing" it. Then it get's finally executed. Consequent executions are way faster because the graph building is already done. But for a single run of a simple calculation, TF will always be slower in graph mode (because it is not designed for it). In other words, for the second cyclic routine we have skiped many pre-precessing opreation like building computational graph.

I thinik this is the reason causing the run time difference between different cyclic routine. In general, we often test single final model in one time as common operation. I don't know report run time result of the second cyclic routine is fair enough since many works of your team are built on tensorflow, many of which **did** just provide single final model to test in one routine. And I think many following researcher also reported the one routine result by using your team's code. You and your team are the expert of this research field, what's your opinion on this?

**Comment by HaoZhang1018** [comment]
Thank you for pointing out this issue worth discussing. As you mentioned, initializing the model for the first time is more time consuming. We found that this phenomenon not only occurs between different cycles, but also between different images in the same cycle. For example, I test the squeeze network on 8 pairs of infrared and visible images for two cycles, and the information is as follows:

@2080ti:/data/IR_VIS$ CUDA_VISIBLE_DEVICES=2 python test_fuse.py
2021-11-22 16:40:55.276129: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2021-11-22 16:40:58.515992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:86:00.0
totalMemory: 10.73GiB freeMemory: 10.57GiB
2021-11-22 16:40:58.516041: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2021-11-22 16:40:58.952277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-22 16:40:58.952322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0
2021-11-22 16:40:58.952330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N
2021-11-22 16:40:58.952798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10210 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:86:00.0, compute capability: 7.5)
Testing [0] success,Testing time is [1.669065]
Testing [1] success,Testing time is [0.009776]
Testing [2] success,Testing time is [0.008890]
Testing [3] success,Testing time is [0.008805]
Testing [4] success,Testing time is [0.008550]
Testing [5] success,Testing time is [0.088225]
Testing [6] success,Testing time is [0.003843]
Testing [7] success,Testing time is [0.004061]
2021-11-22 16:41:01.568081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2021-11-22 16:41:01.568149: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-22 16:41:01.568160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0
2021-11-22 16:41:01.568170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N
2021-11-22 16:41:01.568396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10210 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:86:00.0, compute capability: 7.5)
Testing [0] success,Testing time is [0.070252]
Testing [1] success,Testing time is [0.008931]
Testing [2] success,Testing time is [0.008577]
Testing [3] success,Testing time is [0.008966]
Testing [4] success,Testing time is [0.008424]
Testing [5] success,Testing time is [0.004003]
Testing [6] success,Testing time is [0.003770]
Testing [7] success,Testing time is [0.003805]

It is worth noting that the first 5 images have the same size, while the last 3 images have the same size.  It can be seen that when fusing the first pairs of images, the running time is relatively long. Then when fusing the second to fifth pairs of images (same size as the first pairs), the running time is not much different from that in the second cycle. Similar phenomenons appear in the last three pairs of images. In summary, the running time changes significantly in the first cycle when the size of the test image changes. For other images, the running time in the first cycle is not much different from that in the second cycle. When using the model to fuse video frames in practical applications, it makes sense to consider that the image size is fixed. At this time, except for the initial few frames, the time required for subsequent fusion should be considered not much different from the second cycle. From this perspective, we advocate reporting and comparing the running time of the second cycle. It is also possible to choose to report the running time required for fusing images other than the first few frames. 

The above is our opinion, and I hope it can be helpful to you.
